//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investors2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Account1 = new HashSet<Account>();
            this.FinancialDocLines = new HashSet<FinancialDocLine>();
            this.FinancialDocLines1 = new HashSet<FinancialDocLine>();
        }
    
        public int AccountID { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string AccountLocation { get; set; }
        public bool AnalyticalAccount { get; set; }
        public byte BalanceGroup { get; set; }
        public Nullable<int> SyntheticAccountID { get; set; }
    
        public virtual ICollection<Account> Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual ICollection<FinancialDocLine> FinancialDocLines { get; set; }
        public virtual ICollection<FinancialDocLine> FinancialDocLines1 { get; set; }
    }
}
