//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investors2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentGroup
    {
        public DocumentGroup()
        {
            this.DocumentTypes = new HashSet<DocumentType>();
            this.FinancialDocs = new HashSet<FinancialDoc>();
        }
    
        public int DocumentGroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupShortName { get; set; }
        public int GroupOrder { get; set; }
    
        public virtual ICollection<DocumentType> DocumentTypes { get; set; }
        public virtual ICollection<FinancialDoc> FinancialDocs { get; set; }
    }
}
