//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investors2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.FinancialDocs = new HashSet<FinancialDoc>();
        }
    
        public int DocumentTypeID { get; set; }
        public string TypeName { get; set; }
        public string TypeShortName { get; set; }
        public int CategoryAccountSide { get; set; }
        public Nullable<int> DefaultDocumentGroup { get; set; }
        public bool WarehouseDocumentType { get; set; }
    
        public virtual DocumentGroup DocumentGroup { get; set; }
        public virtual ICollection<FinancialDoc> FinancialDocs { get; set; }
    }
}
