//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investors2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialDocLine
    {
        public int FinancialDocLineID { get; set; }
        public int FinancialDocID { get; set; }
        public Nullable<System.DateTime> LineDate { get; set; }
        public int CurrencyID { get; set; }
        public decimal Amount { get; set; }
        public int DebetID { get; set; }
        public int CreditID { get; set; }
        public bool MainLine { get; set; }
        public Nullable<int> BudgetItemID { get; set; }
        public string PayCode { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> VatRate { get; set; }
        public Nullable<int> DisbursementDocID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual FinancialDoc FinancialDoc { get; set; }
        public virtual FinancialDoc FinancialDoc1 { get; set; }
    }
}
