//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investors2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.FinancialDocs = new HashSet<FinancialDoc>();
            this.FinancialDocs1 = new HashSet<FinancialDoc>();
        }
    
        public int PartnerID { get; set; }
        public byte PhysicalPerson { get; set; }
        public string PartnerName { get; set; }
        public string PartnerTitle { get; set; }
        public string PartnerCode { get; set; }
        public Nullable<int> PartnerTypeID { get; set; }
        public string TerritorialCodeSEZ { get; set; }
        public bool BlockedPartner { get; set; }
        public bool LockedPartner { get; set; }
        public bool ProductSupplier { get; set; }
        public bool ProductWarehouse { get; set; }
        public bool Forwarder { get; set; }
        public bool SemoSubscriber { get; set; }
        public int TaxTypeID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string WebURL { get; set; }
        public string Fax { get; set; }
        public string Comments { get; set; }
        public string CommentsPrintable { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public string PhysicalPersonFirstName { get; set; }
        public string PhysicalPersonIdentityNo { get; set; }
        public string PhysicalPersonTerritorialCode { get; set; }
        public Nullable<bool> PhysicalPersonAdvancePartner { get; set; }
        public Nullable<byte> PhysicalPersonGender { get; set; }
        public string PhysicalPersonPassportOrganization { get; set; }
        public string PhysicalPersonPassportNo { get; set; }
        public Nullable<System.DateTime> PhysicalPersonPassportDate { get; set; }
        public string PhysicalPersonTaxDocumentSerial { get; set; }
        public string PhysicalPersonTaxDocumentNo { get; set; }
        public string PhysicalPersonTaxDocumentOrganization { get; set; }
        public string PhysicalPersonTaxRegNo { get; set; }
        public Nullable<bool> PhysicalPersonPensioner { get; set; }
        public Nullable<bool> PhysicalPersonPrisoner { get; set; }
        public Nullable<int> PhysicalPersonTaxSocialTypeID { get; set; }
        public Nullable<System.DateTime> PhysicalPersonBirthDate { get; set; }
        public Nullable<int> PhysicalPersonIncomeTypeID { get; set; }
        public Nullable<bool> PhysicalPersonURVNamount { get; set; }
        public string PhysicalPersonFirstNameDative { get; set; }
        public string PartnerNameDative { get; set; }
        public string PhysicalPersonFirstNameAccusative { get; set; }
        public string PartnerNameAccusative { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string GLNCode { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
    
        public virtual ICollection<FinancialDoc> FinancialDocs { get; set; }
        public virtual ICollection<FinancialDoc> FinancialDocs1 { get; set; }
    }
}
